filebeat.inputs:
- type: log
  enabled: true
  # Change this to the directory of where your Zeek logs are stored
  paths:
    - /usr/share/honeypot/*.log
  #json.keys_under_root: true
  #fields_under_root: true

#----------------------------- Kafka output --------------------------------
# output.kafka:
#   # Place your HELK IP(s) here (keep the port).
#   hosts: ["<HELK-IP>:9092"]
#   topic: "zeek"
#   max_message_bytes: 1000000

# output.logstash:
#   hosts: ["logstash:5044"]

output.elasticsearch:
  hosts: ["elasticsearch"]
  username: "elastic"
  password: "changeme"

setup.kibana:
  host: "kibana"